### ISSUE TITLE
Powered By Humanitarian Toolbox link does not work

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#206] opened 2015-11-07 21:28 UTC
Powered by HTBox link which appears under the social media buttons on many pages does not link to anything.  On hover, the mouse points as though it can be selected, but nothing happens.

![image](https://cloud.githubusercontent.com/assets/8798159/11017425/5ab3e376-8553-11e5-8bb5-c0689b397bd3.png)

**Comment by ResaWildermuth** [comment] 2015-11-07 21:52
This is a duplicate of issue #142

**Comment by BillWagner** [comment] 2015-11-08 19:07
closing as duplicate of #142

**Closed by BillWagner** 2015-11-08 19:07 UTC
