### ISSUE TITLE
Database Operation failed error

### ISSUE THREAD

**Issue by palittle** [HTBox/allReady#538] opened 2016-02-20 18:35 UTC
While creating a new campaign, I was entering a postal code and clicked to enter (which submitted the form) and the following error message came up (`http://allready-d.azurewebsites.net/Admin/Campaign/Edit`) 

> A database operation failed while processing the request.
> 
> DbUpdateException: An error occurred while updating the entries. See the inner exception for details. 
> SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Location_PostalCodeGeo_PostalCodePostalCode". The conflict occurred in database "allready-d", table "dbo.PostalCodeGeo", column 'PostalCode'. 
> There are pending model changes for AllReadyContext
> Scaffold a new migration for these changes and apply them to the database from the command line:
> 
> > dnx ef migrations add [migration name] 
> > dnx ef database update

**Comment by tonysurma** [comment] 2016-02-20 18:54
this is a duplicate of #470 I believe

**Closed by tonysurma** 2016-02-20 18:54 UTC
