### ISSUE TITLE
User profile - Make email editable or remove/add like phone number

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#296] opened 2015-11-09 04:50 UTC
The user should be able to access the profile form after initial set-up to make edits.  Perhaps as part of a drop-down from the username on the top right. 

![image](https://cloud.githubusercontent.com/assets/8798159/11026158/5ba63a74-865a-11e5-83f2-a7c6bd88a167.png)

**Comment by ksk100** [comment] 2015-11-16 09:30
Are there any aspects of the user's profile which need to be editable, but which aren't already editable via the standard manage screen (the one you get if you click on the user's email)?

**Comment by tonysurma** [comment] 2015-11-16 23:56
Now that that is all working I think everything is editable that needs to be (some day we have to deal with email changes) but there may be some value in adding a UX addition like a drop down arrow or some indication that your name is clickable / takes you to the page to edit them.

Maybe a small menu might be good and this can be 'Profile' as soon we will have other items for a user as well (like seeing all the tasks they volunteered for in one place)

**Comment by tonysurma** [comment] 2015-11-17 04:48
Definitely need a way to edit email if I typo it when creating my account then I can never change it.  We can do it with phone number currently.

**Comment by BillWagner** [comment] 2015-11-17 12:45
@tonysurma How would that scenario (mis-typed email) work when the email addr isn't confirmed? Delete user and re-create? Admin only?

**Comment by MisterJames** [comment] 2015-11-17 13:36
So, the email address is currently being used as the username. We'll need to have a think through on this to make sure that the impact here is understood.

 1. If the user changes their email, we would need to reconfirm it
 1. We probably shouldn't change the primary email until they've confirmed the new one (to prevent accidental lock outs or mal-intent)
 1. We should likely consider a preferred email address, or a campaign-specific email address

Thoughts?

**Comment by stevejgordon** [comment] 2016-01-08 08:55
I'm not 100% sure how best to tackle this yet but could have a try in a branch if no one is currently progressing this one?

@MisterJames 1 and 2 makes sense to me and perhaps we use a couple of additional DB fields to track this. For item 3 I'm perhaps not clear on how you see that working though? Are you proposing a user could store multiple emails (similar to PayPal) with one marked as primary?

**Comment by mheggeseth** [comment] 2016-01-09 13:28
I'm not sure I understand @MisterJames 3rd item either, but we already have a way to specify an alternate email when volunteering. That alternate email so neither confirmed or associated with the user in a permanent way though.

**Comment by stevejgordon** [comment] 2016-01-09 19:52
Maybe the simplest starting point is just a request to change pw with confirmation before final committal. I'll have a play and get something going which we can adjust as necessary.

**Comment by stevejgordon** [comment] 2016-01-10 19:43
I've got this in progress locally. Items I'm adding / steps I'm taking are:

- [x] Update model to support a proposed new email
- [x] Update manage view with link to change email
- [x] Add a change email view and controller
- [x] Validation to reconfirm the user password takes place before any changes are made. A check to ensure the proposed new email is not already registered also occurs
- [x] Update DB with proposed email in new column and send confirmation email
- [ ] Handle confirmation link to change email and remove the proposed field
- [ ] Add ability to resend the confirmation to the proposed mailbox - Leverage existing process
- [x] UI change in manage Index so that a user can see an email address is pending
- [ ] Possibly add option to cancel the email change request

**Comment by stevejgordon** [comment] 2016-01-30 16:42
Wondering if this can be closed based on merged PR #484 or if more is required here?

**Comment by BillWagner** [comment] 2016-02-19 16:55
This can be closed per PR #484. It looks like it did not get automatically closed when that PR was merged.

**Closed by BillWagner** 2016-02-19 16:55 UTC
Labels: P2
