### ISSUE TITLE
I crashed the server with invalid input.

### ISSUE THREAD

**Issue by jona6629** [HTBox/allReady#1336] opened 2016-10-05 18:18 UTC
I think I crashed the server.  Try this repro:
1. Make a new user account  Put an invalid phone number, I put 999
2. Click on your user profile on the top right to add skills to your profile
3. at the bottom of the page add three skills using the + button
4. try to submit.  It should prompt you with all the info that is invalid
5. Click reload button at the top of the browser
Crash

**Comment by wadewachs** [comment] 2016-10-06 19:28
This was a report of some of the testing that was happening around Tuesday night. We don't know that this is what actually caused the infinite loops, but I asked him to enter the issue in the event that it helps troubleshoot the skills related infinite loop that we created with some bit of Data Tuesday night.

**Comment by mgmccarthy** [comment] 2016-10-11 01:01
@wadewachs I just tried to reproduce this locally and could not. When I hit the submit button, I was was prompted to fill in the info that was missing.

**Comment by wadewachs** [comment] 2016-10-11 11:55
This was a report of one of the things that was going on Tuesday night around the time we crashed the server. It is possible this is a red herring, and not the actual cause. I had Jonathan report this as an issue in the event it helped track things down. If following the steps doesn't create the infinite loop failure, feel free to close this issue.

**Comment by tonysurma** [comment] 2016-10-11 11:56
Thx @mgmccarthy for verifying.  I gave the db that causes the infinite loop to @misterjames as we don't know the cause but was pretty sure it wasn't this specifically/alone

**Closed by tonysurma** 2016-10-11 11:56 UTC
Labels: bug
