### ISSUE TITLE
finish unit tests for AllReady.Areas.Admin.Controllers.EventController(EventAdminController.cs)

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#684] opened 2016-04-14 13:21 UTC
@tonysurma, @MisterJames please label with "jump-in". Part of Issue #620

some tests exist, but the rest are stubbed out in:
AllReady.UnitTest.Areas.Admin.Controllers.EventAdminControllerTests

**Comment by SteveKennedy** [comment] 2016-05-26 04:42
I'm looking to jump-in on this one.  Did this class disappear?

**Comment by mgmccarthy** [comment] 2016-05-26 12:21
@SteveKennedy, what happened here is there was a global renaming of anything called "activity" to "event". Looking at the history of the `EventControllerTests`, it used to be named `ActivityControllerTests`, so I'll change the name of this Issue to reflect the name change.

Looking at `EventControllerTests`, it looks like there are still plenty of tests to be written, so feel free to start into them.

Thanks

**Comment by jonatwabash** [comment] 2016-08-06 21:27
@tonysurma could I take this one? I'm pretty sure I can get a couple of tests done this weekend.

**Comment by tonysurma** [comment] 2016-08-06 23:32
sure, thanks

**Comment by mgmccarthy** [comment] 2016-11-02 12:04
@tonysurma, this is a dupe of Issue #617. One of these should be closed and just leave the one open to represent the work that still needs to be done

**Comment by tonysurma** [comment] 2016-11-03 10:24
leaving this open

**Comment by c0g1t8** [comment] 2017-03-22 07:48
@tonysurma I've been looking at these tests as a way to get more familiar with Moq.  I've filled in a few of the stubs and found some bad tests.  Please assign me 😄

**Comment by c0g1t8** [comment] 2017-03-22 19:16
@mgmccarthy Question: Looking at the stub for **CreateGetSendsCampaignSummaryQueryWithCorrectCampaignId**.  Not sure what the intent of this test.  **CampaignSummaryQuery** is not publicly exposed in the **EventController** class.

**Comment by mgmccarthy** [comment] 2017-03-22 19:30
@c0g1t8, I'm not too sure what you mean "is not publicly exposed"...

The EventController class's Create method looks like this:
```
[Route("Admin/Event/Create/{campaignId}")]
public async Task<IActionResult> Create(int campaignId)
{
    var campaign = await _mediator.SendAsync(new CampaignSummaryQuery { CampaignId = campaignId });
    if (campaign == null || !User.IsOrganizationAdmin(campaign.OrganizationId))
    {
        return Unauthorized();
    }

    var viewModel = new EventEditViewModel
    {
        CampaignId = campaign.Id,
        CampaignName = campaign.Name,
        TimeZoneId = campaign.TimeZoneId,
        OrganizationId = campaign.OrganizationId,
        OrganizationName = campaign.OrganizationName,
        StartDateTime = DateTimeTodayDate(),
        EndDateTime = DateTimeTodayDate()
    };

    return View("Edit", viewModel);
}
```

the test stub should test that the CampaignSummaryQuery is being sent with the correct CampaignId

**Comment by c0g1t8** [comment] 2017-03-22 19:37
@mgmccarthy Looked into the other tests.  Should this be **CreateGetReturnsCorrectView_AndCorrectCampaignID**?

**Comment by c0g1t8** [comment] 2017-03-22 19:59
@mgmccarthy Okay - just got it.  The test to ensure that **CampaignSummaryQuery** is called once with the correct parameters. 😄   Thanks.

**Comment by mgmccarthy** [comment] 2017-03-22 19:59
@c0g1t8, it does not return CampaignId, it returns EventEditViewModel.

Please do a search for other controller's that use mediator.SendAsync in the code. Then find that controller's unit tests. There are a ton of examples that show how to test what the mediator is sending

The `CreateGetSendsCampaignSummaryQueryWithCorrectCampaignId` unit only tests this line of the action method:
`var campaign = await _mediator.SendAsync(new CampaignSummaryQuery { CampaignId = campaignId });`

**Comment by c0g1t8** [comment] 2017-03-22 22:21
@mgmccarthy I think I've found a possible bug.  I'm working on `PostEventFileSendsEventByEventIdQueryWithCorrectEventId`.  

![image](https://cloud.githubusercontent.com/assets/23250332/24223324/d5114790-0f12-11e7-97bb-41aa2fe88fe2.png)

The order of parameters calling `UploadEventImageAsync `appear to be incorrect in `PostEventFile `method of the `EventController `class.

I'm not sure what the course of action should be.  Do I fix the controller and submit it as part of the updated tests?  Do I file a separate issue?

Looking for guidance.

**Comment by c0g1t8** [comment] 2017-03-22 22:28
Don't know how I removed myself.  Can one of the powers to be please reassign me. 😄

**Comment by tonysurma** [comment] 2017-03-22 23:08
I think because you removed yourself I can't assign you...

**Comment by mgmccarthy** [comment] 2017-03-22 23:25
c0g1t8, check the implementation of IImageService.UploadEventImageAsync and see where it actually puts the image (aka, the path to the file). I believe the implementation uses Azure blob storage, so my guess is that the blob path would differ based on the word "Event" or something along those lines.

**Comment by mgmccarthy** [comment] 2017-03-22 23:28
@c0g1t8 

> I'm not sure what the course of action should be. Do I fix the controller and submit it as part of the updated tests? Do I file a separate issue?

First check the implementation. If the two params (organizationId and eventId) are "backwards" as your finding suggests, then open a separate issue for it. It should not be part of the unit test work you're doing.

Thanks

**Comment by tonysurma** [comment] 2017-03-23 01:43
regardless of github not allowing re-assignment (don't know why) you can make a PR - thanks!

**Comment by c0g1t8** [comment] 2017-03-23 04:13
@mgmccarthy Working on `MessageAllVolunteersReturnsHttpNotFoundResult_WhenEventIsNull`.  `MessageAllVolunteers` does not have a code path that returns `HttpNotFoundResult`.

```
       [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MessageAllVolunteers(MessageEventVolunteersViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var eventsOrganizationId = await _mediator.SendAsync(new OrganizationIdByEventIdQuery { EventId = viewModel.EventId });
            if (!User.IsOrganizationAdmin(eventsOrganizationId))
            {
                return Unauthorized();
            }

            await _mediator.SendAsync(new MessageEventVolunteersCommand { ViewModel = viewModel });

            return Ok();
        }
```

Skip this test or create a new issue?  I'm thinking the latter.

**Comment by c0g1t8** [comment] 2017-03-23 06:05
@mgmccarthy Dug farther.  

```
public async Task<int> Handle(OrganizationIdByEventIdQuery message)
{
    var @event = await _context.Events.AsNoTracking()
        .Include(e => e.Campaign)
        .ThenInclude(c => c.ManagingOrganization)
        .SingleAsync(t => t.Id == message.EventId);

    return @event.Campaign.ManagingOrganization.Id;
}
```

The implementation assumes `@event` will always will be found.  I think this is a bad assumption. 

I'm thinking we need to re-implement `MessageAllVolunteers` with `EventByEventIdQuery` instead.  This will allow for a check for when _Event is null_.

```
public async Task<Event> Handle(EventByEventIdQuery message)
{
    // TODO: can we leave off some of these .Include()?
    return await _context.Events
        .Include(a => a.Location)
        .Include(a => a.Campaign).ThenInclude(c => c.ManagingOrganization)
        .Include(a => a.RequiredSkills).ThenInclude(rs => rs.Skill).ThenInclude(s => s.ParentSkill)
        .Include(a => a.VolunteerTasks).ThenInclude(t => t.AssignedVolunteers).ThenInclude(tu => tu.User)
        .Include(a => a.VolunteerTasks).ThenInclude(t => t.RequiredSkills).ThenInclude(ts => ts.Skill)
        .SingleOrDefaultAsync(a => a.Id == message.EventId);
}
```
The queries don't match and I don't know the domain well enough to know if that's a valid option.

Thoughts?

**Comment by mgmccarthy** [comment] 2017-03-23 15:25
@c0g1t8 

> Working on MessageAllVolunteersReturnsHttpNotFoundResult_WhenEventIsNull. MessageAllVolunteers does not have a code path that returns HttpNotFoundResult

I'd delete the test stub. FYI, these test stubs were created a while ago, and there have been code changes to the classes the test stubs test, so some of them might no longer be relevant or even make sense.

**Comment by mgmccarthy** [comment] 2017-03-23 15:43
@c0g1t8 

> The implementation assumes @event will always will be found. I think this is a bad assumption.

No, this is a good assumption. 

Where did the eventId come from that we're using to look up the event? It was passed in as a value on the MessageEventVolunteersViewModel:
```
public async Task<IActionResult> MessageAllVolunteers(MessageEventVolunteersViewModel viewModel)
```

what code calls the MessageAllVolunteers action method? The \Areas\Admin\Views\Event\Details.cshtml view:
```
<form asp-area="Admin" asp-controller="Event" asp-action="MessageAllVolunteers" method="post">
    <div class="modal-body">
        <input type="hidden" value="@Model.Id" name="eventId" id="message-eventId">
        <div class="form-group">
            <label for="subject" class="control-label">Subject</label>
            <input type="text" class="form-control wide" name="subject" id="messageVolunteersModal-subject">
        </div>
        <div class="form-group">
            <label for="message-text" class="control-label">Message</label>
            <textarea rows="4" class="form-control wide" name="message" id="messageVolunteersModal-message"></textarea>
            <span id="messageCharacterCount" class="text-muted"></span>
        </div>
        <div class="alert alert-info" role="alert">Sending message...</div>
        <div class="alert alert-success" role="alert"><i class="fa fa-check"></i> Message sent</div>
        <div class="alert alert-danger" role="alert"></div>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" id="sendMessageToVolunteers" class="btn btn-primary">Send Message</button>
    </div>
</form>
```

you can see above, we're passing in the `@Model.Id` for the `eventId` value. What loads the Details.cshtml page and give the @Model.Id its value? The EventAdminController.Details action method, which has the EventId on the EventDetailQuery viewmodel.

So the value is guaranteed on the read that loads the Details.cshtml page. If you look a the code, you'll see that if EventDetailQuery returns null, the page will not be loaded.

So, what would be the reason that the eventId would not be there? It's guaranteed to be loaded by the Details action method and it's a hidden value on the Details.cshtml view.

The only logical reason for that lookup to fail is if someone deleted the event between the time you loaded the details page and clicked on the Message All Volunteers button. I'm not too sure if you can delete an event (and if you can, why you'd want to delete an event), but both ops (delete the event, or Message all Volunteers) are both performed by a user with admin access. My initial guess is this will be one person, or a small group of people that are allowed to do admin-based operations per Campaign and or Org.

Try not to put .SingleOrDefault on every query "just in case". This makes it tougher for new contributors to understand the system. If there is a query using .SingleOrDefault, the first question I ask myself is "why would this value/query return null?". Then I work backwards from the query to see how the parameter(s) supplied by the query are created/loaded. Almost every time you do this, you can see that the Default part of the query can be left off b/c there is either no logical reason for the query to fail, or there is a VERY small edge case around non-collaborative data where something MIGHT be missing.

I wrote a blog post about this very thing. Give it a read if you'd like:
[http://www.michaelgmccarthy.com/2017/01/27/optimize-for-the-happy-path-null-checks/](http://www.michaelgmccarthy.com/2017/01/27/optimize-for-the-happy-path-null-checks/)

**Comment by c0g1t8** [comment] 2017-03-23 22:00
@mgmccarthy 

> I'd delete the test stub. FYI, these test stubs were created a while ago, and there have been code changes to the classes the test stubs test, so some of them might no longer be relevant or even make sense.

Deleting `MessageAllVolunteersReturnsHttpNotFoundResult_WhenEventIsNull` and proceeding onwards. 😄

**Comment by c0g1t8** [comment] 2017-03-23 22:06
@mgmccarthy 

>I wrote a blog post about this very thing. Give it a read if you'd like:
http://www.michaelgmccarthy.com/2017/01/27/optimize-for-the-happy-path-null-checks/

Very insightful.  I do agree that we often write too much _defensive code_ especially when you are in control of all the entry points.

**Comment by tonysurma** [comment] 2017-03-23 23:04
@c0g1t8 after you accept the invite I can assign you again.  Thanks

**Comment by c0g1t8** [comment] 2017-03-24 00:56
@mgmccarthy - I found another test that looks like it needs to be deleted `DeleteConfirmedSendsEventDetailQueryWithCorrectEventId`

Below is the code for the method:
```
[HttpPost, ActionName("Delete")]
[ValidateAntiForgeryToken]
public async Task<IActionResult> DeleteConfirmed(DeleteViewModel viewModel)
{
    if (!viewModel.UserIsOrgAdmin)
    {
        return Unauthorized();
    }

    await _mediator.SendAsync(new DeleteEventCommand { EventId = viewModel.Id });

    return RedirectToAction(nameof(CampaignController.Details), "Campaign", new { area = "Admin", id = viewModel.CampaignId });
}
```

I'm pretty sure that it needs to be deleted since `EventDetailQuery` is never called.

**Comment by mgmccarthy** [comment] 2017-03-24 01:04
@c0g1t8, yep, you can delete that stub. Thanks!

**Comment by c0g1t8** [comment] 2017-03-24 01:16
FYI - almost complete 😄 Only 13 more EditPost tests left.

**Comment by c0g1t8** [comment] 2017-03-24 10:22
@mgmccarthy 

Renaming `EditPostAddsValidationErrorsToModelStateErrors_WhenEventDetailsModelValidatorHasErrors `to `EditPostAddsValidationErrorsToModelStateErrors_WhenEventEditViewModelValidatorHasErrors`.

Renaming `EditPostReturnsCorrectView_WhenEventDetailsModelValidatorHasErrors` to `EditPostReturnsCorrectView_WhenEventEditViewModelValidatorHasErrors`.

Trying to be descriptive and accurate.  I am assuming that will be alright with you.

**Comment by c0g1t8** [comment] 2017-03-24 19:19
@mgmccarthy 

I'm working on `EditPostInvokesUploadEventImageAsyncWithTheCorrectParameters_WhenModelStateIsValid_AndFileUploadIsNotNull_AndFileUploadIsAnAcceptableImageContentType` and need to Mock `IsAcceptableImageContentType`.  It's an extension method.

I've done the following:
```
            var formFile = new Mock<IFormFile>();
            formFile
                .Setup(x => x.IsAcceptableImageContentType())
                .Returns(true);
```

But when I run the test, I get the following:
![image](https://cloud.githubusercontent.com/assets/23250332/24310122/e003bf82-108b-11e7-9bce-1cb6da971321.png)

Can you provide me some guidance?  How do I mock an extension method?

**Comment by c0g1t8** [comment] 2017-03-24 20:49
@tonysurma Can you assign me?  There are only 5 tests left to be completed.  They all require the ability to mock extension methods.  But in the mean time, I'm going to create a PR of what I've completed.

**Comment by c0g1t8** [comment] 2017-03-24 23:05
@mgmccarthy 

I've been doing some research.  It looks like you can't use Moq to Mock an extension in general 😞.  I did find [Mocking Static Methods for Unit Testing](http://adventuresdotnet.blogspot.ca/2011/03/mocking-static-methods-for-unit-testing.html).  But that requires changing the implementation of the extension.

Should I _skip_ these last remaining tests?  Have we encountered this issue before?

**Comment by c0g1t8** [comment] 2017-03-25 01:01
@mgmccarthy 

Figured it out 😄.  Looks like what I needed to do was not to Mock `IsAcceptableImageContentType` directly.  A clue was provided by looking at it's implementation.  

```
        public static bool IsAcceptableImageContentType(this IFormFile file)
        {
            var isImageContentType = false;
            var contentType = file.ContentType.ToLowerInvariant();

            if (contentType == "image/png" ||
                contentType == "image/jpeg" ||
                contentType == "image/gif")
            {
                isImageContentType = true;
            }

            return isImageContentType;
        }
```

What I needed to mock was `ContentType`.  I came up with the following:
```
            var formFile = new Mock<IFormFile>();
            formFile
                .Setup(x => x.ContentType)
                .Returns("image/png");
```

This worked.  I'm proceeding to complete the remainder of the tests now.

**Comment by c0g1t8** [comment] 2017-03-25 03:03
Renaming `EditPostDoesNotInvokeDeleteImageAsyncWithTheCorrectParameters_WhenModelStateIsValid_AndFileUploadIsNotNull_AndFileUploadIsAnAcceptableImageContentType_AndThereIsAnExistingImage` to 
`EditPostDoesNotInvokeDeleteImageAsyncWithTheCorrectParameters_WhenModelStateIsValid_AndFileUploadIsNotNull_AndFileUploadIsAnAcceptableImageContentType_AndAnExistingImageDoesNotExist`.

To provide a better description of the test.

**Comment by mgmccarthy** [comment] 2017-03-25 11:42
@c0g1t8 

> Figured it out :smile:. Looks like what I needed to do was not to Mock IsAcceptableImageContentType directly. A clue was provided by looking at it's implementation.

Nice job!

**Closed** 2017-03-26 15:10 UTC
Labels: jump-in, unit testing
