### ISSUE TITLE
STARWest_Expand Toggle is broken ... Viewable data is hidden

### ISSUE THREAD

**Issue by ChicquillaLewis** [HTBox/allReady#1354] opened 2016-10-06 18:53 UTC
Description: Expand Toggle is broken ... Viewable data is hidden

This error limits the user to see the pull down options when the field is expanded.

![screenshot 2016-10-06 at 11 29 32 am](https://cloud.githubusercontent.com/assets/22665710/19166361/099c2460-8bbc-11e6-875a-5d52c6d20548.png)

Steps to Recreate: 
Access the web site.
Login as the admin user.
Press the dashboard button
Select a current event
On a task, DO NOT press the triangle to expand the task area
On the mark complete button, press the triangle to expand the pull down options.

Error: Options are not viewable.

Suggested Resolution: Fix the toggle triangle

In addition a work around for the failing toggle is described below:

On a task, press the triangle to expand the task area
On the mark complete button, press the triangle to expand the pull down options.
press the mark complete button and the toggle functionality is restored

![screenshot 2016-10-06 at 11 29 32 am](https://cloud.githubusercontent.com/assets/22665710/19166381/199205ec-8bbc-11e6-886f-01403f3a9bde.png)

**Comment by tonylambert** [comment] 2016-11-03 01:43
I attempted to reproduce this but to no avail. I tried Chrome and Edge on Windows 10 Anniversary edition.

Here is a video showing the steps I went through: http://screencast.com/t/C8WtwVakqsY

**Comment by tonylambert** [comment] 2016-11-03 23:52
@tonysurma, @mgmccarthy - Hey guys. I am not sure how things like this are dealt with yet on this project, but since you both helped me on my last PR, I am reaching out directly to you via this comment for this issue. I was going to try to fix this issue, but I am unable to reproduce it (or an reproducing it incorrectly). How should I proceed? In my comment above you can see me attempting to reproduce it in a video.

Please advise.

Thanks!

**Comment by mgmccarthy** [comment] 2016-11-04 00:32
@tonylambert cc @tonysurma 

I think anything reported by STARWest is some type of automated testing suite/lab? So, it could be that suite didn't work properly, or it could be this issues is so old it's already been fixed...

If you can't reproduce it, then to me, it's no longer an issue.

**Comment by tonysurma** [comment] 2016-11-04 01:04
Hello @tonylambert and @mgmccarthy 

Thanks for asking and always feel free.  STARWest was a QA / Software Quality / Testing Conference and just like we have code-a-thons at dev conferences they had a test-a-thon.  You can tell issues also from there as they are very high quality and well documented 😸 which is great.

Further as @mgmccarthy said if you can't reproduce it then its no longer an issue and we close it.

Some things get fixed by other changes side effects, some things are broken in one build missing a file, etc.  Thanks for throughly working to verify this bug.  I will close it.

**Closed by tonysurma** 2016-11-04 01:04 UTC
Labels: jump-in, UI/UX

**Comment by mgmccarthy** [comment] 2016-11-04 11:11
@tonylambert, if you're looking for another PR to start, there is a large list of jump-ins available, mostly to do with unit tests needing to be completed. Also, there are a handful of bugs out there as well.
