### ISSUE TITLE
Tasks cannot be collapsed after they are opened.

### ISSUE THREAD

**Issue by calaharie** [HTBox/allReady#1334] opened 2016-10-05 18:14 UTC
Open the Application and navigate to the following link:
http://allready-d.azurewebsites.net/Event/12

Click on a task.
Click on it again.
The task will not collapse.

**Comment by julianharty** [comment] 2016-10-05 21:57
The Campaign Info expand/collapse icon has a similar flaw, the collapse doesn't happen.

Tested on
Version: 1.0.0.0 8a77b3a

**Comment by wadewachs** [comment] 2016-10-06 23:44
@calaharie  - We selected you as a prize winner from the test lab. Either try to find me before you leave the conference, or send me your email address and I will get the prize to you.

Thanks for all of your help at the lab.

**Comment by calaharie** [comment] 2016-10-20 18:18
@wadewachs calaharie@gmail.com

This notification was hidden in my e-mail, glad I happened to see it!

**Comment by wadewachs** [comment] 2016-11-04 19:54
@calaharie I forwarded your email over to the folks at Techwell that have your prize. If you don't get it in a couple weeks let me know.

-Wade-

**Comment by tonysurma** [comment] 2016-11-04 21:35
@tonylambert is this the same/duplicate of #1354 we just closed?  Thanks

**Comment by tonylambert** [comment] 2016-11-05 01:28
@tonysurma - The bug is still present at the azure website linked to above, but running the latest in master on my machine at home I do not see the issue. The build on the azure website appears to be from August timeframe.

So, in short, yes, I think this one is no longer an issue. I think you can close it.

**Comment by tonysurma** [comment] 2016-11-05 02:06
Hmm, that site is auto deployed from master latest, I will need to see what is up.  Either the auto deploy stopped or something else.  Thanks

**Comment by tonylambert** [comment] 2016-11-05 02:13
Well. I assumed that the number in the screenshot below was the short Git commit hash:

http://screencast.com/t/chI57n6Q

Perhaps that's not right?

**Comment by tonysurma** [comment] 2016-11-05 03:00
@tonylambert - nope that is totally valid.  I just checked and the site is auto deploying but it looks like the git version isn't bieng updated (I will create an issue tomorrow AM for that).  However now it is a mystery of why this works locally for you but not on live.  Missing JS or something I wonder...

**Comment by slaneyrw** [comment] 2017-03-01 20:34
Just checked the original link and the Tasks do collapse, both on clicking the same task again or on another task.

**Comment by tonysurma** [comment] 2017-03-01 20:36
thanks @slaneyrw it may have been fixed by another in the time since then.

**Closed by tonysurma** 2017-03-01 20:36 UTC
Labels: jump-in, UI/UX
