### ISSUE TITLE
web app: tinymce CDN link broken

### ISSUE THREAD

**Issue by BingYHu** [HTBox/allReady#1480] opened 2016-11-10 22:33 UTC
Chrome debugger showed that "Failed to get ...." error message for tinymce

**Comment by tonylambert** [comment] 2016-11-11 00:20
This is a duplicate of #1455.

**Comment by tonylambert** [comment] 2016-11-16 02:09
@tonysurma - This is a dup and should be closed.

**Comment by EmilyLuijbregts** [comment] 2016-12-03 21:02
Comment from Tonylambert - closed as a duplicate

**Closed by EmilyLuijbregts** 2016-12-03 21:02 UTC
