### ISSUE TITLE
Unhandled exception occurs when you click to open an expired activity

### ISSUE THREAD

**Issue by palittle** [HTBox/allReady#618] opened 2016-03-23 05:31 UTC
Here is the error message that came up:
An unhandled exception occurred while processing the request.

JsonSerializationException: Self referencing loop detected for property 'ManagingOrganization' with type 'AllReady.Models.Organization'. Path 'tasks[1].RequiredSkillObjects[0].OwningOrganization.Campaigns[0]'.
Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)

Microsoft.AspNet.Mvc.ViewFeatures.JsonHelper.Serialize(Object value)
Asp.ASPV__Views_Activity__ActivityScripts_cshtml.<ExecuteAsync>d__30.MoveNext() in _ActivityScripts.cshtml
        var modelStuff = @Json.Serialize(new

**Comment by dangle1** [comment] 2016-03-26 02:00
Please assign this one to me.

**Comment by dangle1** [comment] 2016-03-26 02:30
@palittle can you please provide more specifics on this one? Steps to reproduce, data used when error occurred, etc.? I'm having trouble reproducing this on my machine right now.

**Comment by curts** [comment] 2016-05-18 18:35
I am not able to recreate this issue either.  I am not able to locate the file `_ActivityScripts.cshtml` as referenced in the original issue.

**Comment by vishal123** [comment] 2016-05-18 20:09
```_ActivityScripts.cshtml``` may have been renamed to ```_EventScripts.cshtml```
See ```\AllReadyApp\Web-App\AllReady\Views\Event\_EventScripts.cshtml```

**Comment by robrich** [comment] 2016-06-05 00:22
http://allready-d.azurewebsites.net/Campaign/9 -> click on "Installs" -> blows up loading http://allready-d.azurewebsites.net/Event/1.  I'm not able to reproduce this locally either.

**Comment by tonysurma** [comment] 2016-06-05 15:13
Hmmm so only happens on the deployed site?

**Comment by VishalMadhvani** [comment] 2016-06-05 17:06
The exception is thrown if a Task in the Event has a RequiredSkill owned by an Organisation.

The code is currently serialising the Skill's Entity so I've introduced a SkillViewModel without navigation properties that will get serialised instead.

See PR #807

**Comment by robrich** [comment] 2016-06-07 16:26
https://github.com/HTBox/allReady/pull/807 solves this ... together with @tonysurma flashing the database.  Well done.  We can close this.

**Closed** 2016-06-07 18:18 UTC
Labels: P1
