### ISSUE TITLE
As an user, I can register on the site using my social network accounts

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#15] opened 2015-07-20 13:02 UTC
Related to #3 we need to fully document this requirement and decide what bugs/enhancements are needed to fully complete the story in all environments

**Comment by shawnwildermuth** [comment] 2015-10-20 21:10
I'll take this if someone would assign it.

**Comment by bcbeatty** [comment] 2015-10-20 21:13
I can help out too. I just finished an app that has a Facebook login using ngCordova

**Comment by shawnwildermuth** [comment] 2015-10-20 21:15
BC, since you've done this before, why don't you take it and i'll focus on the password management and the database stuff.

**Comment by shawnwildermuth** [comment] 2015-10-20 21:36
BC is doing this, not me.

**Comment by bcbeatty** [comment] 2015-10-22 02:12
Followed the following steps on https://docs.asp.net/en/latest/security/sociallogins.html to create a Facebook app using the name **"All Ready"** and a test app **"All Ready - Test1"**
I'm unable to get the FB user's email address, even though I'm adding the email scope in Startup.cs

**Comment by bcbeatty** [comment] 2015-10-23 21:32
Most of this task is setting configuration settings to match the app id and secret keys. These will be different for each developer and the Azure sites. 
There are some gotchas when using the different oath providers:

1. Facebook isn't returning email, even though it is scoped and exists for user. http://stackoverflow.com/questions/25069816/facebook-email-field-return-null-even-if-the-email-permission-is-set-and-acce
2. Twitter, even though the application will provide a callback url, you must provide one. https://support.twitter.com/forms/platform
3. Twitter. By default twitter will not expose a user's email. Your app must be whitelisted. https://docs.fabric.io/android/twitter/request-user-email-address.html
4. Microsoft, you cannot use IIS Express, this is by design. http://stackoverflow.com/questions/25049480/asp-net-mvc-microsoft-live-account-authentication-on-localhost

**Comment by MisterJames** [comment] 2015-11-08 01:17
@tonysurma I think we can close this one based on our conversation.

I think that we can create a few other issues to talk about volunteer on-boarding and when to prompt for things like email an sms

**Comment by BillWagner** [comment] 2015-11-08 17:04
@bcbeatty Both Twitter and Facebook work fine. I'm getting an error on the Microsoft account. I'll open a new issue for that, and close this one. See Issue #246 for the Microsoft account issue.

**Closed by BillWagner** 2015-11-08 17:04 UTC
Labels: P1, requirement, volunteer workflow, web app
