### ISSUE TITLE
submit and cancel links become unactive - should throw error handiling

### ISSUE THREAD

**Issue by sandygarcia** [HTBox/allReady#1309] opened 2016-10-05 01:28 UTC
click on upcoming campaigns - Working Smoke Detectors Save Lives

Nothing happens when I submit a comment for a volunteer

<script>prompt ("donate now")</script>

**Comment by tonysurma** [comment] 2016-10-21 04:04
this is a duplicate of another issue

**Closed by tonysurma** 2016-10-21 04:04 UTC
Labels: bug, duplicate
