### ISSUE TITLE
Exception Thrown When Viewing Itinerary in Admin

### ISSUE THREAD

**Issue by dchristensen** [HTBox/allReady#1601] opened 2016-12-04 16:52 UTC
I got this error `InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first.` when trying to view an itinerary from the dev system.

![InvalidOperationException](https://cloud.githubusercontent.com/assets/427494/20867655/fbdaf968-ba06-11e6-9f7b-c30cde398f3f.png)

and the relevant part of the stack trace:

![Stack Trace](https://cloud.githubusercontent.com/assets/427494/20867658/23408e6e-ba07-11e6-8db4-eb5fd65f922c.png)

**Comment by stevejgordon** [comment] 2016-12-18 11:54
Looks like something in the data might be throwing off our quite complex query to build up the view model. I've tried a few scenarios locally and I can't get this to blow up in the same way.

@tonysurma - I tried to access the Db in Azure but I'll need my latest IP added to the firewall rules. I'd like to have a look over the data to see if that points to the cause.

**Comment by stevejgordon** [comment] 2016-12-20 19:47
Update: found the code causing the break and reviewing the best solution. I think it's not an issue locally as my database is accepting multiple active record sets. I'll hopefully have time to finalise the solution in the next few days.

**Comment by stevejgordon** [comment] 2016-12-21 13:17
@tonysurma This issue is caused by EF trying to read multiple datasets at the same time, which happens in our query to build up the admin itinerary model. This doesn't occur locally as we enable Multiple Active Result Sets (MARS) on the connstring. 

We have a couple of options. 1) We add MultipleActiveResultsets=true to the end of the Azure connstring used for the test site (wherever that is defined). Or 2) We update the offending code. I do have some code that I believe fixes the problem, but it's a bit more verbose. If you see no issue using MARS then it might be best to update the connstring and see if that solves the problem? If you prefer we update the code also, I can finish off the fix and get a PR in.

Generally we shouldn't see cases where this is present, but depending on how we need to work with the ef query to shape the model it might crop up again. If we do decide not to use this in Azure, then I would propose we also update the dev connstring to not enable it, so we see issues during dev time.

**Comment by tonysurma** [comment] 2016-12-21 15:25
@stevejgordon I added that to the connection string (I thought it was there already) and have stopped/started the site so it should be 'live'

Can you verify before we close this issue?

Thanks

**Comment by stevejgordon** [comment] 2016-12-21 16:16
Whoop! Looks good to me, I can access the itinerary details page now that was blowing up yesterday.

**Closed by stevejgordon** 2016-12-21 16:16 UTC
Labels: bug, P1
