### ISSUE TITLE
NullReferenceException when viewing manage account page (/Manage)

### ISSUE THREAD

**Issue by VishalMadhvani** [HTBox/allReady#956] opened 2016-06-25 19:33 UTC
Logged in as Administrator@example.com
When viewing the account management page http://localhost:48408/Manage
A NullReferenceException is thrown.

I assume this is test data related as no exception is thrown on http://allready-d.azurewebsites.net/Manage

@tonysurma This can be labelled Jump In

**Comment by cj-taylor** [comment] 2016-06-28 13:38
@tonysurma I'll be looking into this one.

**Comment by mheggeseth** [comment] 2016-08-06 21:20
@tonysurma I can't reproduce this. Looking at the code, the only way this could have happened is if `var user = GetCurrentUser()` returns null which then causes `user.ToViewModel()` to blow up. However, this should never happen because the `[Authorize]` attribute at the top of `ManageController` ensure no action should enter unless a user is logged in. I suggest closing because there's really nothing to do here.

**Closed** 2016-08-06 21:20 UTC
Labels: P1
