### ISSUE TITLE
Our appveyor build should precompile the razor views

### ISSUE THREAD

**Issue by BillWagner** [HTBox/allReady#260] opened 2015-11-08 18:55 UTC
This is waiting on some new support from asp.net 5, but when that is supported, we should build the razor views as part of the cheks on PRs.

**Comment by dpaquette** [comment] 2015-11-11 01:26
Experimented with this a little today and could not get the build to fail when there were errors on a razor page. I will revisit once the next version of aspnet5 is released.

**Comment by mheggeseth** [comment] 2016-08-06 21:30
@tonysurma Can close this as dupe of #972.

**Closed** 2016-08-06 22:10 UTC
