### ISSUE TITLE
Social Share Buttons for Campaigns do not work

### ISSUE THREAD

**Issue by Harmonym** [HTBox/allReady#214] opened 2015-11-07 22:06 UTC
It looks like the social share button functionality for a campaign has not yet been set up.
![image](https://cloud.githubusercontent.com/assets/8798159/11017743/3cbb8c2e-855e-11e5-9031-c806188b2ff6.png)

**Comment by JesseLiberty** [comment] 2015-11-27 23:46
Duplicate of issue #188 (closed)

**Comment by BillWagner** [comment] 2015-11-29 02:18
@JesseLiberty is right. Duplicate. Closed.

**Closed by BillWagner** 2015-11-29 02:18 UTC
