### ISSUE TITLE
write unit tests for AllReady.Controllers.EventController

### ISSUE THREAD

**Issue by mgmccarthy** [HTBox/allReady#662] opened 2016-04-06 00:06 UTC
@tonysurma please label with "jump-in". Part of Issue #620

stubs are provided in:
AllReady.UnitTest.Controllers.EventControllerTests.

**Comment by digitaldrummerj** [comment] 2016-10-30 23:47
@tonysurma I see in the PR that has been merged that you put a closes this issue comment in but the issue is still open.  Is it still a valid issue?

**Comment by mgmccarthy** [comment] 2016-11-02 11:57
@tonysurma @digitaldrummerj the unit tests exist and this Issue can be closed

**Closed** 2016-11-03 10:26 UTC
Labels: jump-in
